title: Geeky Nuggets
description: Jonathan Foucher's blog <span class="amp">&amp;</span> web development notebook
clean_desc: Jonathan Foucher's blog & web development notebook

include:
    - .gitlab-ci.yml

sass:
    sass_dir: _sass
    style: compressed

url: https://jfoucher.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: /:year/:month/:title.html

kramdown:
  input: GFM
  syntax_highlighter: rouge

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate, compass, normalize-scss, rouge, kramdown]
paginate: 6

plugins: [jekyll-seo-tag]

navigation:
 - title: Home
   url: /
 - title: About
   url: /about.html
 - title: Contact
   url: /contact.html
 - title: Projects
   url: /projects.html
 - title: Videos
   url: /videos.html

social:
   github: jfoucher
   twitter: jfoucher
   facebook: jfoucher
   email: jfoucher@gmail.com

collections:
  projects:
    permalink: /projects/:path
  videos:
    permalink: /videos/:path.html
    output: true

google_analytics: "UA-8465441-2"
